steps:
  - imports:
      align: file
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
      space_surround: false
      post_qualify: false
      group_imports: false
      group_rules:
        - match: ".*"
          sub_group: "^[^.]+"
  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
      language_prefix: LANGUAGE
columns: 80
newline: lf
cabal: true
